type error_code =
  | Unknown_error
  | Function_contains_free_vars
  | Invalid_escape_character
  | Constructor_is_lambda
  | Constructor_has_zero_arguments
  | Constructor_is_not_function
  | Not_implemented
  | Impossible
  | Polymorphic_var_not_found
  | Option_not_inferred
  | Untagged_as
  | Invalid_type_as
  | Unrecognised_character
  | Struct_not_found
  | Unexpected_codegen_type
  | Library_not_found
  | Invalid_character_literal
  | Unterminated_inline_C
  | Unknown_type_size
  | Not_a_generic_type
  | Not_a_numerical_type
  | Double_declaration
  | No_return
  | Unterminated_string
  | Reserved_identifier
  | Invalid_character_in_string
  | Type_mismatch
  | Lambda_void_param
  | Function_void_param
  | Static_comp_archetype
  | Static_comp_model
  | Model_implements_non_archetype
  | Model_missing_required_field
  | If_non_boolean_guard
  | While_non_boolean_guard
  | For_non_boolean_guard
  | Unknown_identifier
  | Banish_non_model
  | Wrong_return
  | Non_equatable_type
  | Wrong_number_parameters
  | ADT_Wrong_constructor_type
  | ADT_Invalid_constructor
  | Static_comp_lambda
  | Out_of_bounds
  | Invalid_subscript
  | Invalid_summon
  | Private_access
  | Invalid_access
  | Cannot_infer_type_for_nothing
  | Function_vararg_not_last
  | Keyword_expected
  | Top_level_definition_expected
  | ADT_Missing_constructors
  | Unexpected_token
  | Empty_program
  | Expected_token
  | Invalid_archesum
  | Invalid_fundef
  | Missing_braces
  | Invalid_match
  | Invalid_lambda
  | Invalid_make
  | Type_expected
  | Invalid_constructor
  | File_not_found
  | Internal_error
  | External_error
  | ADT_Unsame_constructor_types
  | ADT_Unification_unexpected
  | ADT_Constructor_does_not_construct
[@@deriving enum, show { with_path = false }]
